### ISSUE TITLE
vue2接入后报错

### ISSUE THREAD

**Issue by AmbitionJs** [tengmaoqing/vite-plugin-qiankun#10]
vue2，qiankun项目，接入后本地调试报错：
![image](https://user-images.githubusercontent.com/45837094/141229954-77d3bcdc-9ddf-483b-8f92-735b7ecab389.png)

**Comment by tengmaoqing** [comment]
从报错信息看是 main.js 加载404 了。
可以描述清楚一点环境，以及一个可以复现的demo

**Comment by AmbitionJs** [comment]
> 从报错信息看是 main.js 加载404 了。 可以描述清楚一点环境，以及一个可以复现的demo

仓库地址：https://github.com/AmbitionJs/vite-qiankun-vue2-demo.git
具体的情况：当qiankun主、微应用同时接入vite后就会出现上述报错，子应用能够单独启动。不知是不是我哪里没有设置好，麻烦大佬帮忙看看，谢谢

**Comment by myloverhxx** [comment]
> > 从报错信息看是 main.js 加载404 了。 可以描述清楚一点环境，以及一个可以复现的demo
> 
> 仓库地址：https://github.com/AmbitionJs/vite-qiankun-vue2-demo.git 具体的情况：当qiankun主、微应用同时接入vite后就会出现上述报错，子应用能够单独启动。不知是不是我哪里没有设置好，麻烦大佬帮忙看看，谢谢

遇到一样的问题...请问解决了么

**Comment by myloverhxx** [comment]
> > > 从报错信息看是 main.js 加载404 了。 可以描述清楚一点环境，以及一个可以复现的demo
> > 
> > 
> > 仓库地址：https://github.com/AmbitionJs/vite-qiankun-vue2-demo.git 具体的情况：当qiankun主、微应用同时接入vite后就会出现上述报错，子应用能够单独启动。不知是不是我哪里没有设置好，麻烦大佬帮忙看看，谢谢
> 
> 遇到一样的问题...请问解决了么

index.html 文件引入main.js路径问题，改成` <script type="module" src="/src/main.js"></script>`

**Comment by AmbitionJs** [comment]
> > > > 从报错信息看是 main.js 加载404 了。 可以描述清楚一点环境，以及一个可以复现的demo
> > > 
> > > 
> > > 仓库地址：https://github.com/AmbitionJs/vite-qiankun-vue2-demo.git 具体的情况：当qiankun主、微应用同时接入vite后就会出现上述报错，子应用能够单独启动。不知是不是我哪里没有设置好，麻烦大佬帮忙看看，谢谢
> > 
> > 
> > 遇到一样的问题...请问解决了么
> 
> index.html 文件引入main.js路径问题，改成` <script type="module" src="/src/main.js"></script>`

兄弟牛皮！！！
