### ISSUE TITLE
加载vite微应用的时候超时错误   timeouts.js:149 single-spa minified message #31

### ISSUE THREAD

**Issue by lemonly14** [tengmaoqing/vite-plugin-qiankun#13]
![image](https://user-images.githubusercontent.com/41465479/144749052-aa81c0e8-a239-4808-8033-67e2aa21e8a7.png)

**Comment by xiaofanchuan159** [comment]
打包之后再集成，就没有问题了

**Comment by danealiu** [comment]
同遇到这个问题了，请问怎么解决呢 @tengmaoqing

**Comment by tengmaoqing** [comment]
> 同遇到这个问题了，请问怎么解决呢 @tengmaoqing

如果vite子应用加载比较慢超过30s会有这个问题。Single-spa 超时检测，但是只要最终能加载完就应该没影响的
