### ISSUE TITLE
支持vue3.2+vite2+ts 吗？

### ISSUE THREAD

**Issue by duguangyan** [tengmaoqing/vite-plugin-qiankun#18]

**Comment by tengmaoqing** [comment]
支持的，这里和react或者 vue没关系

**Comment by duguangyan** [comment]
有朋友遇到 这个 错误吗？ 在本地没问题 ，部署到linux服务器 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by tengmaoqing** [comment]
和你部署的 nginx 配置有关系。
js资源访问服务器获得了 html文件，结合你的项目目录检查下nginx配置

**Comment by FuFuHao** [comment]
@tengmaoqing 我也是遇到这个问题，没有部署，就是在开发模式

**Comment by tengmaoqing** [comment]
> @tengmaoqing 我也是遇到这个问题，没有部署，就是在开发模式

要看你具体问题和配置，开发模式出现这个问题，一般就是js，css资源命中了devserve的index页面
