### ISSUE TITLE
乾坤的生命周期里是不是缺少了update

### ISSUE THREAD

**Issue by yizhilian1314** [tengmaoqing/vite-plugin-qiankun#19]
![image](https://user-images.githubusercontent.com/20395986/162117636-4c1d1b74-60a7-460f-a542-d9eb2ace5a74.png)
![image](https://user-images.githubusercontent.com/20395986/162117771-4ea97717-58da-49a9-944b-cb6018ea7335.png)

**Comment by tengmaoqing** [comment]
是的，目前没支持。我抽空加一下

**Comment by tengmaoqing** [comment]
最新版本已经添加update 以及相应的demo
