### ISSUE TITLE
打包后资源无法独立部署

### ISSUE THREAD

**Issue by terry-guo** [tengmaoqing/vite-plugin-qiankun#2]
<script type="module" crossorigin="" src="">import('/assets/index.32752bbf.js').finally(() => {
    const qiankunLifeCycle = window.moudleQiankunAppLifeCycles && window.moudleQiankunAppLifeCycles['crm-static'];
    if (qiankunLifeCycle) {
      window.proxy.vitemount((props) => qiankunLifeCycle.mount(props));
      window.proxy.viteunmount((props) => qiankunLifeCycle.unmount(props));
      window.proxy.vitebootstrap(() => qiankunLifeCycle.bootstrap());
    }
  
          })</script>

如上，打包后的index.html文件中有一条script, 会导入打包后的js然后执行一些操作，这时候放在微前端里面是能直接打开的。。但是通过 "start": "http-server ./dist -p 7106 --cors" 命令开启的服务，直接访问  http://127.0.0.1:7106,  是不会运行main.js中的

if (!qiankunWindow.__POWERED_BY_QIANKUN__) {
 // 独立运行的
  render()
}
我这边想到的是，在打包后的html里面插入一条script，判断当前是乾坤运行环境，生成一条<script type="module" crossorigin="" src="/assets/index.32752bbf.js"></script> 插入到body中

**Comment by terry-guo** [comment]
我改了下您这个插件src>index.ts的部分逻辑，新增了creatDefaultRuntime 方法，我本地构建之后是能正常使用的，既能嵌套到乾坤里面用，又能实现独立部署的时候用

const creatDefaultRuntime = (moduleSrc: any) => {
  return `
  const qiankunWindow = window.proxy || window;
  if (!qiankunWindow.__POWERED_BY_QIANKUN__) {
    // 独立运行
    const ele = document.createElement('script')
    ele.src = '${moduleSrc}'
    ele.setAttribute('type', 'module')
    ele.setAttribute('crossorigin', '')
    document.body.appendChild(ele)
  }
  `;
}
const htmlPlugin: PluginFn = (qiankunName: string) => {
  let isProduction: boolean;
  let devWBase: string;
  return {
    // enforce: 'post',
    name: 'qiankun-html-transform',
    configResolved(config) {
      isProduction = config.command === 'build' || config.isProduction;
      devWBase = `http://127.0.0.1:${config.server.port || 3000}${config.base}`;
    },
    transformIndexHtml(html: string) {
      const $ = cheerio.load(html);
      const moduleTags = $('script[type=module]');
      if (!moduleTags || !moduleTags.length) {
        return;
      }
      let moduleSrc
      moduleTags.each((i, moduleTag) => {
        const script$ = $(moduleTag)
        moduleSrc = script$.attr('src');
        if (isProduction) {
          script$.attr('src', '');
          script$.html(`import('${moduleSrc}').finally(() => {
            ${createImportFinallyResolve(qiankunName)}
          })`);
          return;
        }
      });
      $('body').append(`<script>${creatDefaultRuntime(moduleSrc)}</script>`);
      $('body').append(`<script>${createQiankunHelper(qiankunName)}</script>`);
      const output = $.html();
      return output;
    },
  };
};

**Comment by tengmaoqing** [comment]
抱歉，上个版本修改出问题了。因为 script标签上 src属性没去掉，导致独立运行时没获取main.ts。
晚点修复下

**Comment by tengmaoqing** [comment]
1.0.7 已经修复了

**Comment by terry-guo** [comment]
> 1.0.7 已经修复了

nice

**Comment by daiwanxing** [comment]
你好，我目前用的 `vite-plugin-qiankun@1.0.15` 打包后，仍然是
```js
 <script crossorigin="">
            import("/subapp/xx/xx/assets/index-5cddfe2a.js").finally(() => {
                const qiankunLifeCycle =
                    window.moudleQiankunAppLifeCycles && window.moudleQiankunAppLifeCycles["MFEOfficeCenter"];
                if (qiankunLifeCycle) {
                    window.proxy.vitemount((props) => qiankunLifeCycle.mount(props));
                    window.proxy.viteunmount((props) => qiankunLifeCycle.unmount(props));
                    window.proxy.vitebootstrap(() => qiankunLifeCycle.bootstrap());
                    window.proxy.viteupdate((props) => qiankunLifeCycle.update(props));
                }
            });
        </script>
``` 

导致子应用无法请求自己域名下的资源而请求的是主应用下的。如何解决啊
