### ISSUE TITLE
import-html-entry]: error occurs while executing normal script <script type="module">

### ISSUE THREAD

**Issue by xuhaichaoy** [tengmaoqing/vite-plugin-qiankun#20]
![image](https://user-images.githubusercontent.com/37998995/162379515-85320d3b-7a82-470b-844c-5ae34f3afee4.png)
![image](https://user-images.githubusercontent.com/37998995/162379622-530da446-9495-4875-ae82-19f567bc3e49.png)
![image](https://user-images.githubusercontent.com/37998995/162379661-d8415f7e-f4a5-423b-9846-b44422f68771.png)

**Comment by BTBMan** [comment]
@xuhaichaoy 我也有同样的问题 请问你是怎么解决的
