### ISSUE TITLE
貌似基于vite的vue3子应用目前无法支持？？

### ISSUE THREAD

**Issue by hejun200613224** [tengmaoqing/vite-plugin-qiankun#25]
根据别人的react子应用的demo能够调通，但是基于vue3的子应用貌似无法正常运行dev

**Comment by tengmaoqing** [comment]
支持的，可以列出你的具体错误看看

**Comment by hejun200613224** [comment]
错误就是跟直接引用type="module"的js一样，子应用加载之后运行过程中报错（eval方法执行不支持type module 的js）

**Comment by tengmaoqing** [comment]
example 里面有vue3 的例子可以参考下呢
