### ISSUE TITLE
vite设置base后script类型为module的@vite/client资源未进行编译

### ISSUE THREAD

**Issue by magao1991** [tengmaoqing/vite-plugin-qiankun#26]
![DC06CA8E-D983-4560-99F6-E191D4DFA972](https://user-images.githubusercontent.com/4714474/168129369-2d4352bb-20f5-4c22-bba3-405aaed6b193.png)

这里未匹配成功
module2DynamicImport($, $('script[src=/@vite/client]').get(0))

**Comment by tengmaoqing** [comment]
1.0.15 修复了这个问题
