### ISSUE TITLE
咨询一个webpack配置问题

### ISSUE THREAD

**Issue by godkun** [tengmaoqing/vite-plugin-qiankun#29]
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/26134303/170656698-3f628741-02a3-407f-9c3f-a987d9810dec.png">

如上图所示：用vie-plugin-qiankun 配置的话，图中配置是不是可以不需要了

**Comment by tengmaoqing** [comment]
是的，用vie-plugin-qiankun的应用不需要了
