### ISSUE TITLE
无法在qiankun中多个位置loadMicroApp同一个子应用

### ISSUE THREAD

**Issue by Hxgh** [tengmaoqing/vite-plugin-qiankun#3]
![image](https://user-images.githubusercontent.com/17973025/129300902-9be18925-099f-477f-857e-e1a408e5fe2a.png)

**Comment by tengmaoqing** [comment]
你这里多个位置是同一个url下的。还是不同url下的呢？

目前我在不同url下是没问题的。 可以贴一下当前使用版本，以及主应用调用方式。

另外： 使用loadMicroApp，在主应用里面组件写在的时候，微应用也要注意一并手动unmount()。

**Comment by Hxgh** [comment]
更新到1.0.9，
webpack的主应用：prod dev下无论相同还是不同url都能用了
vite的主应用:prod都行，但dev下接入报错overlay.ts:185 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vite-error-overlay" has already been used with this registry
我不知道是不是我的问题或者情况特殊.

**Comment by tengmaoqing** [comment]
可以看下 #4  提供的demo，他也说有这个报错。实际上我跑他demo的时候没有出现这个错误，那边经过修改后是可以正常运行的。

如果仍然有问题，可以提供一个demo看看

**Comment by rxliuli** [comment]
吾辈没有 load 同一个子应用哦，它们都是不同的子应用

> 可以看下 #4 提供的 demo，他也说有这个报错。实际上我跑他 demo 的时候没有出现这个错误，那边经过修改后是可以正常运行的。
> 
> 如果仍然有问题，可以提供一个 demo 看看

**Comment by tengmaoqing** [comment]
> 更新到1.0.9，
> webpack的主应用：prod dev下无论相同还是不同url都能用了
> vite的主应用:prod都行，但dev下接入报错overlay.ts:185 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vite-error-overlay" has already been used with this registry
> 我不知道是不是我的问题或者情况特殊.

https://github.com/vitejs/vite/issues/4470  vite之前的版本有这个问题，目前已经修复了。 我使用的是 vite@2.5.0 ，没有这个报错

**Comment by tengmaoqing** [comment]
先关闭了，如果有问题可以再开一个issue
