### ISSUE TITLE
ts 错误：An argument for 'microOption' was not provided.

### ISSUE THREAD

**Issue by aladdin-add** [tengmaoqing/vite-plugin-qiankun#31]
vite-plugin-qiankun@npm:1.0.14
按照文档说明增加vite配置，得到ts报错：
![image](https://user-images.githubusercontent.com/13050025/171113013-1a11105a-560f-430b-ad32-0234b0b5dd81.png)

**Comment by enpitsuLin** [comment]
个人认为这个参数应该可选

**Comment by tengmaoqing** [comment]
增加了可选链
