### ISSUE TITLE
主应用会报这个错误[import-html-entry]

### ISSUE THREAD

**Issue by thinkive** [tengmaoqing/vite-plugin-qiankun#32]
主应用使用官方example里面的main，子应用使用vite-plugin-qiankun/example/vue3sub,子应用独立启动正常，主应用调用子应用，运行正常，但是控制台会报错
![image](https://user-images.githubusercontent.com/10447320/175458438-d72eb240-4408-4a2a-89a3-103f1eb47f44.png)

**Comment by tengmaoqing** [comment]
看起来是子应用设置了base吧。1.0.15已经修复了这个开发环境问题

**Comment by impengmoumou** [comment]
最新版v1.0.15，开发环境主应用仍然报这个错误

**Comment by rookiePrgrmer** [comment]
同样也是最新的1.0.15，主应用报这个错误

**Comment by jingjingzhao** [comment]
同样也是最新的1.0.15，主应用报这个错误

**Comment by AboyL** [comment]
> 最新版v1.0.15，开发环境主应用仍然报这个错误

这个问题有解决吗？

**Comment by a-big-cutie** [comment]
没有解决这个问题吗？我在点击子应用的时候，也碰到这个问题了。vue3+vite
