### ISSUE TITLE
react+vite 已经可以了，但 vue+vite 还不行。。。

### ISSUE THREAD

**Issue by rxliuli** [tengmaoqing/vite-plugin-qiankun#4]
> 可复现示例：<https://github.com/rxliuli/micro-app-demo>

```js
overlay.ts:185 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vite-error-overlay" has already been used with this registry
```
vite 配置

```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import qiankun from 'vite-plugin-qiankun'

//useDevMode 开启时与热更新插件冲突
const useDevMode = true

export default defineConfig({
  plugins: [
    //TODO vue 仍然不能正常支持
    vue(),
    qiankun('vue-app', {
      useDevMode,
    }),
  ],
  server: {
    port: 3102,
    cors: true,
  },
})

```

src/main.ts

```ts
import { createApp, App as VueInstance } from 'vue'
import App from './App.vue'

import {
  renderWithQiankun,
  qiankunWindow,
} from 'vite-plugin-qiankun/dist/helper'
import {
  createRouter,
  createWebHashHistory,
  Router,
  RouterHistory,
} from 'vue-router'
import { routeList } from './constants/routeList'

let app: VueInstance | null = null
let history: RouterHistory | null = null
let router: Router | null = null

function render(props: any) {
  const { container } = props
  app = createApp(App)
  history = createWebHashHistory(
    qiankunWindow.__POWERED_BY_QIANKUN__ ? '/app/vue-app' : '',
  )
  router = createRouter({
    history: history,
    routes: routeList,
  })
  app.use(router)
  app.mount(
    container
      ? container.querySelector('#root')
      : document.getElementById('root'),
  )
}

renderWithQiankun({
  mount(props) {
    console.log('vue mount')
    render(props)
  },
  bootstrap() {
    console.log('bootstrap')
  },
  unmount(props: any) {
    console.log('vue unmount')
    app!.unmount()
    ;(app!._container as HTMLDivElement).innerHTML = ''
    app = null
    router = null
    history!.destroy()
    history = null
  },
})

if (!qiankunWindow.__POWERED_BY_QIANKUN__) {
  render({})
}

```

----

react 版本其实也有个不影响运行的错误

```js
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vite-error-overlay" has already been used with this registry
```

**Comment by rxliuli** [comment]
可以添加一个 vite+vue 的示例么？

**Comment by tengmaoqing** [comment]
我运行了一下你的demo， vue 是能够起来的啊。

![image](https://user-images.githubusercontent.com/15967520/129693380-3dd881f5-62d4-47e8-8008-26ad33a254cf.png)

不过页面会一直自动刷新，不知道你是哪个逻辑控制着刷新。
我使用的linux跑的代码，你可以提供一下你的环境信息。
解决一下代码自动刷新的问题然后我们再排查一下吧。

**Comment by tengmaoqing** [comment]
> 可以添加一个 vite+vue 的示例么？

这周我抽空看看加一下

**Comment by rxliuli** [comment]
> 我运行了一下你的 demo， vue 是能够起来的啊。
> 
> ![image](https://user-images.githubusercontent.com/15967520/129693380-3dd881f5-62d4-47e8-8008-26ad33a254cf.png)
> 
> 不过页面会一直自动刷新，不知道你是哪个逻辑控制着刷新。
> 我使用的 linux 跑的代码，你可以提供一下你的环境信息。
> 解决一下代码自动刷新的问题然后我们再排查一下吧。

哦，是因为主应用修改为了 history 路由，子应用是 hash 路由

**Comment by rxliuli** [comment]
稍等

**Comment by rxliuli** [comment]
已添加错误示例：<https://github.com/rxliuli/micro-app-demo/tree/bug_vite-plugin-qiankun>

![vite-vue 错误示例](https://user-images.githubusercontent.com/24560368/129695434-958720be-0e45-42fb-ae93-731e32cb792f.gif)

**Comment by tengmaoqing** [comment]
![image](https://user-images.githubusercontent.com/15967520/129699827-20ce2c01-e272-452c-9097-f5f498dc9ccf.png)

这里面base没有设置正确，导致你的vue 404了

**Comment by rxliuli** [comment]
> ![image](https://user-images.githubusercontent.com/15967520/129699827-20ce2c01-e272-452c-9097-f5f498dc9ccf.png)
> 
> 这里面 base 没有设置正确，导致你的 vue 404 了。 按照我截图里面调整后就可以正常展示了
> 
> ![image](https://user-images.githubusercontent.com/15967520/129700787-1f331be2-d66a-4f7e-ba6c-2525c43dea19.png)

吾辈这儿似乎还是不行，可否发个 git patch？

**Comment by tengmaoqing** [comment]
我只改了上面两行代码。
对比一下环境  vite@2.5.0 吧.
然后我这边没有你说  "vite-error-overlay" 这个错误， https://github.com/vitejs/vite/issues/4023  vite前面的版本好像是有报这个错误

**Comment by rxliuli** [comment]
> 我只改了上面两行代码。
> 对比一下环境 vite@2.5.0 吧.
> 然后我这边没有你说 "vite-error-overlay" 这个错误， [vitejs/vite#4023](https://github.com/vitejs/vite/issues/4023) vite前面的版本好像是有报这个错误

不，现在错误变成了

```js
[Vue Router warn]: A hash base must end with a "#":
"#/app/vue-app" should be "#".
```

**Comment by tengmaoqing** [comment]
这只是一个警告， 你还有一行最关键的代码没改

![image](https://user-images.githubusercontent.com/15967520/129721516-403c6b21-8378-400a-8f54-474233dc4a63.png)

**Comment by rxliuli** [comment]
> 这只是一个警告， 你还有一行最关键的代码没改
> 
> ![image](https://user-images.githubusercontent.com/15967520/129721516-403c6b21-8378-400a-8f54-474233dc4a63.png)

抱歉，是吾辈蠢了。。。

**Comment by rxliuli** [comment]
再次出现了这个问题，但吾辈无法提供一个最小可复现示例，因为吾辈在迁移生产环境的应用。。。

**Comment by rxliuli** [comment]
> 再次出现了这个问题，但吾辈这次无法提供一个最小可复现示例，因为吾辈在迁移生产环境的应用。。。

通过升级生产环境的 vite/vue 解决，具体灵感来自：<https://github.com/tengmaoqing/vite-plugin-qiankun/issues/3#issuecomment-900160311>

另外，qiankun 和 ant-design-vue 一起使用时，子应用的样式影响到父应用的问题一般怎么解决？
吾辈尝试了 shandbox 配置，但并未生效

复现步骤

1. git clone && yarn install
2. cd apps/vue-app && yarn dev
3. cd apps/main-app && yarn dev
4. 打开 <http://localhost:3000/app/vue-app>

![image](https://user-images.githubusercontent.com/24560368/129892710-7b82ce06-725e-4a0a-9052-dfc4adecd790.png)

**Comment by rxliuli** [comment]
> > 再次出现了这个问题，但吾辈这次无法提供一个最小可复现示例，因为吾辈在迁移生产环境的应用。。。
> 
> 通过升级生产环境的 vite/vue 解决，具体灵感来自：[#3 (comment)](https://github.com/tengmaoqing/vite-plugin-qiankun/issues/3#issuecomment-900160311)
> 
> 另外，qiankun 和 ant-design-vue 一起使用时，子应用的样式影响到父应用的问题一般怎么解决？
> 吾辈尝试了 [shandbox 配置](https://qiankun.umijs.org/zh/api#startopts)，但并未生效
> 
> 复现步骤
> 
> 1. git clone && yarn install
> 2. cd apps/vue-app && yarn dev
> 3. cd apps/main-app && yarn dev
> 4. 打开 http://localhost:3000/app/vue-app
> 
> ![image](https://user-images.githubusercontent.com/24560368/129892710-7b82ce06-725e-4a0a-9052-dfc4adecd790.png)

吾辈在 sf 创建了一个问题：<https://segmentfault.com/q/1010000040537727>

**Comment by tengmaoqing** [comment]
乾坤子应用污染父应用样式是官方问题，里面有解释原因，不知道你说的是否是这个意思。
https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%A1%AE%E4%BF%9D%E4%B8%BB%E5%BA%94%E7%94%A8%E8%B7%9F%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E7%9A%84%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB

**Comment by rxliuli** [comment]
> 乾坤子应用污染父应用样式是官方问题，里面有解释原因，不知道你说的是否是这个意思。
> https://qiankun.umijs.org/zh/faq#%E5%A6%82%E4%BD%95%E7%A1%AE%E4%BF%9D%E4%B8%BB%E5%BA%94%E7%94%A8%E8%B7%9F%E5%BE%AE%E5%BA%94%E7%94%A8%E4%B9%8B%E9%97%B4%E7%9A%84%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB

不是，吾辈指的是子应用的样式应用到了父应用，例如 body/h1~h6 这些

**Comment by tengmaoqing** [comment]
乾坤本身不能避免父应用和子应用的样式污染。
如果定位到是因为插件引起的问题，可以重新开一个issue，这个先关闭了哈。
