### ISSUE TITLE
主应用会报这个错误[import-html-entry]

### ISSUE THREAD

**Issue by LKDBABY** [tengmaoqing/vite-plugin-qiankun#6]
![image](https://user-images.githubusercontent.com/88132494/129721731-be02af8c-8a0b-4504-8d40-b26878a77b2c.png)

**Comment by LKDBABY** [comment]
![image](https://user-images.githubusercontent.com/88132494/129722267-039b286b-2c55-4c6d-9359-6447ed37c1cd.png)

**Comment by tengmaoqing** [comment]
什么版本的呢，具体代码是什么？

**Comment by LKDBABY** [comment]
> 什么版本的呢，具体代码是什么？
没问题搞好拉，另外有个点是需要npm i dom-align，dom-align@1.12.2no match

**Comment by tengmaoqing** [comment]
没有直接依赖 dom-align 的地方，可能是你那边有些依赖没有安装好导致的

**Comment by tengmaoqing** [comment]
先关闭了，如果有问题可以再开一个issue

**Comment by thinkive** [comment]
> > 什么版本的呢，具体代码是什么？
> > 没问题搞好拉，另外有个点是需要npm i dom-align，[dom-align@1.12.2no](mailto:dom-align@1.12.2no) match

请问你是在主应用安装这个？还是在子应用？我也遇到这个问题了

**Comment by a-big-cutie** [comment]
我也遇到了，在点击跳转子应用的时候出现的，但是安装 dom-align没有效果呢
