### ISSUE TITLE
以vue为主配置vite与qiankun后，在作为子应用接入后，页面一直重定向跳转

### ISSUE THREAD

**Issue by LiZheGuang** [tengmaoqing/vite-plugin-qiankun#8]
main.ts
`import { App as VueInstance, createApp } from 'vue'
import App from './App.vue'

import {
  qiankunWindow,
  renderWithQiankun,
} from 'vite-plugin-qiankun/dist/helper'
import {
  createMemoryHistory,
  createRouter,
  Router,
  RouterHistory,
  createWebHashHistory
} from 'vue-router'
import { routeList } from './constants/routeList'
// import 'ant-design-vue/dist/antd.less'

let app: VueInstance | null = null
let history: RouterHistory | null = null
let router: Router | null = null

function render(props: any) {
  const { container } = props
  app = createApp(App)
  history = createWebHashHistory(
    // qiankunWindow.__POWERED_BY_QIANKUN__ ? '/app/vue-app' : '',
    qiankunWindow.__POWERED_BY_QIANKUN__ ? '#' : '',
  )
  history = createWebHashHistory()
  router = createRouter({
    history: history,
    routes: routeList,
  })
  app.use(router)
  app.mount(
    container
      ? container.querySelector('#root')
      : document.getElementById('root'),
  )
}

renderWithQiankun({
  mount(props: any) {
    console.log('vue mount')
    render(props)
  },
  bootstrap() {
    console.log('bootstrap')
  },
  unmount(props: any) {
    console.log('vue unmount')
    app!.unmount()
      ; (app!._container as HTMLDivElement).innerHTML = ''
    app = null
    router = null
    history!.destroy()
    history = null
  },
})

if (!qiankunWindow.__POWERED_BY_QIANKUN__) {
  console.log('本地执行')
  render({})
}
`

**Comment by liuestc** [comment]
> 我启用了一个相对干净的主应用，没有发现重复刷新的问题，我猜测，应该还是我本身的问题，我自己再排查下

遇到了相同的问题，请问解决了么，怎么解决的

**Comment by LiZheGuang** [comment]
> > 我启用了一个相对干净的主应用，没有发现重复刷新的问题，我吃饭，应该还是我制造的问题，我再排查下
> 
> 遇到了相同的问题，请问解决了么，怎么解决的

额，我后续没有进行排查，奇怪的是当部署完后以域名的形式接入，没有刷屏的问题，感觉像是本地nginx导致的，我也不清楚。

**Comment by qiaozhu** [comment]
+1 同样无限刷新
具体场景是：
主应用打包后+子应用dev模式  无限刷新
主应用dev模式+子应用dev模式 正常
主应用打包后+子应用打包后 正常

也就是说本地开发 每个人必须分别启动 主应用dev模式+子应用dev模式
